import { Deck } from '@/types';

export const INITIAL_DECKS: Deck[] = [
  {
    id: 'deck-1',
    title: '🧬 Cell Biology & Organelles',
    description: 'Core concepts of cellular architecture, mitochondria, ATP synthesis, and cell membranes.',
    category: 'Biology',
    cards_count: 5,
    due_count: 5,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c1',
        deck_id: 'deck-1',
        card_type: 'multiple_choice',
        front: 'Which organelle is responsible for generating most of the chemical energy needed by the cell (ATP)?',
        back: 'Mitochondria',
        distractors: ['Ribosome', 'Endoplasmic Reticulum', 'Golgi Apparatus'],
        explanation: 'Synthesizes ATP via oxidative phosphorylation using the electrochemical proton gradient across the inner mitochondrial membrane.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c2',
        deck_id: 'deck-1',
        card_type: 'flashcard',
        front: 'What is the primary function of the Ribosome?',
        back: 'Protein translation (translating mRNA into polypeptide chains)',
        explanation: 'Ribosomal subunits coordinate aminoacyl-tRNA molecules to assemble peptide chains corresponding to mRNA codons.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c3',
        deck_id: 'deck-1',
        card_type: 'multiple_choice',
        front: 'Which cellular structure controls the movement of substances into and out of the cell?',
        back: 'Plasma (Cell) Membrane',
        distractors: ['Nuclear Envelope', 'Cytoplasm', 'Lysosome'],
        explanation: 'The amphipathic phospholipid bilayer restricts polar solutes, while embedded channels and pumps regulate selective transit.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c4',
        deck_id: 'deck-1',
        card_type: 'fill_blank',
        front: 'In plant chloroplasts, the light-dependent reactions of photosynthesis occur within the ________ membrane.',
        back: 'thylakoid',
        explanation: 'Thylakoid membranes contain Photosystems I and II, generating the proton gradient that drives ATP synthase.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c5',
        deck_id: 'deck-1',
        card_type: 'flashcard',
        front: 'What enzymatic contents do lysosomes carry, and what is their function?',
        back: 'Acid hydrolases (pH ~4.5-5.0) that degrade endocytosed molecules, damaged organelles, and cellular debris.',
        explanation: 'Proton pumps maintain an acidic lumen; neutral cytosolic pH prevents unintended autolysis if enzymes leak.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'deck-2',
    title: '💻 Modern React & Next.js',
    description: 'Hooks, React Server Components, state management, and web performance patterns.',
    category: 'Computer Science',
    cards_count: 4,
    due_count: 4,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c201',
        deck_id: 'deck-2',
        card_type: 'multiple_choice',
        front: 'In React, what hook is used to perform side effects such as data fetching and subscriptions?',
        back: 'useEffect',
        distractors: ['useState', 'useMemo', 'useCallback'],
        explanation: 'useEffect lets you synchronize a component with an external system after render.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c202',
        deck_id: 'deck-2',
        card_type: 'flashcard',
        front: 'What is the main benefit of React Server Components (RSC)?',
        back: 'Zero bundle size on the client for server-only dependencies, with direct backend resource access.',
        explanation: 'Server components execute only on the server, sending rendered HTML/JSON to the client without adding JS weight.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c203',
        deck_id: 'deck-2',
        card_type: 'fill_blank',
        front: 'To memorize the result of an expensive calculation between re-renders, use the ________ hook.',
        back: 'useMemo',
        explanation: 'useMemo caches the result of a calculation until one of its dependencies changes.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c204',
        deck_id: 'deck-2',
        card_type: 'multiple_choice',
        front: 'What directive declares a file as a Client Component in Next.js App Router?',
        back: '"use client"',
        distractors: ['"use browser"', '"client only"', '"use interactive"'],
        explanation: '"use client" marks the boundary where code can use browser APIs, state, and event listeners.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
];
