import { Deck, Folder } from '@/types';

export const INITIAL_FOLDERS: Folder[] = [
  { id: 'f-pharma', name: 'Pharmacology', icon: 'Pill', color: 'teal', created_at: new Date().toISOString() },
  { id: 'f-medsurg', name: 'Medical-Surgical', icon: 'Stethoscope', color: 'blue', created_at: new Date().toISOString() },
  { id: 'f-nclex', name: 'NCLEX-RN Prep', icon: 'ClipboardCheck', color: 'amber', created_at: new Date().toISOString() },
  { id: 'f-maternal', name: 'Maternal & Pediatrics', icon: 'Baby', color: 'rose', created_at: new Date().toISOString() },
];

export const INITIAL_DECKS: Deck[] = [
  {
    id: 'deck-pharma-1',
    title: 'Cardiac Pharmacology & High-Alert Meds',
    description: 'Antihypertensives, antiarrhythmics, Digoxin safety, and critical antidotes.',
    category: 'Pharmacology',
    folder_id: 'f-pharma',
    cards_count: 4,
    due_count: 4,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c-pharma-1',
        deck_id: 'deck-pharma-1',
        card_type: 'flashcard',
        front: 'What mandatory assessment must the nurse perform prior to administering Digoxin?',
        back: 'Auscultate the apical pulse for 1 full minute; withhold the dose if heart rate is < 60 bpm in adults.',
        explanation: 'Digoxin exerts negative chronotropic effects. Administering it to a bradycardic patient can precipitate complete AV heart block.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-pharma-2',
        deck_id: 'deck-pharma-1',
        card_type: 'multiple_choice',
        front: 'Which adverse reaction to ACE inhibitors represents a life-threatening airway emergency requiring immediate drug cessation?',
        back: 'Angioedema (swelling of lips, tongue, and glottis due to bradykinin buildup)',
        distractors: [
          'Dry, hacking, non-productive cough',
          'Mild postural hypotension upon rising',
          'Transient hyperkalemia of 5.1 mEq/L'
        ],
        explanation: 'Angioedema can cause acute laryngeal edema and asphyxiation. It is an absolute contraindication to re-prescribing ACE inhibitors.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-pharma-3',
        deck_id: 'deck-pharma-1',
        card_type: 'fill_blank',
        front: 'The specific antidote for acute unfractionated heparin toxicity with severe hemorrhage is ________ sulfate.',
        back: 'protamine',
        explanation: 'Protamine sulfate is a strongly basic peptide that combines with strongly acidic heparin to form a stable, inactive salt.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-pharma-4',
        deck_id: 'deck-pharma-1',
        card_type: 'flashcard',
        front: 'Why does hypokalemia (serum potassium < 3.5 mEq/L) dangerously amplify Digoxin toxicity?',
        back: 'Potassium and digoxin compete for identical binding sites on myocardial Na+/K+ ATPase; low potassium allows excessive digoxin binding.',
        explanation: 'Even normal therapeutic digoxin levels can cause fatal arrhythmias when the patient is hypokalemic (e.g. from furosemide diuresis).',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'deck-medsurg-1',
    title: 'Fluid, Electrolyte & Acid-Base Imbalances',
    description: 'Electrolyte shifts, ECG signs, ABG interpretation, and acute nursing interventions.',
    category: 'Medical-Surgical',
    folder_id: 'f-medsurg',
    cards_count: 3,
    due_count: 3,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c-ms-1',
        deck_id: 'deck-medsurg-1',
        card_type: 'multiple_choice',
        front: 'A post-thyroidectomy patient exhibits carpopedal spasm when their blood pressure cuff is inflated for 3 minutes. What sign does this indicate?',
        back: "Trousseau's sign of latent hypocalcemia",
        distractors: [
          "Chvostek's sign of facial nerve hyperirritability",
          "Cullen's sign of retroperitoneal hemorrhage",
          "Kernig's sign of meningeal irritation"
        ],
        explanation: 'Accidental trauma to or removal of the parathyroid glands causes acute hypocalcemia (Ca2+ < 8.5 mg/dL), provoking neuromuscular tetany.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-ms-2',
        deck_id: 'deck-medsurg-1',
        card_type: 'flashcard',
        front: 'What is the earliest and most classic electrocardiogram (ECG) finding of Hyperkalemia?',
        back: 'Tall, narrow, peaked T waves across precordial leads.',
        explanation: 'Elevated extracellular potassium accelerates cardiac repolarization; severe progression leads to PR prolongation, widened QRS, and sine waves.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-ms-3',
        deck_id: 'deck-medsurg-1',
        card_type: 'fill_blank',
        front: 'In uncompensated respiratory acidosis, the arterial blood gas shows pH < 7.35 and an elevated PaCO2 exceeding ________ mmHg.',
        back: '45',
        explanation: 'Hypoventilation causes carbon dioxide retention, driving carbonic acid accumulation and dropping arterial pH below 7.35.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'deck-nclex-1',
    title: 'NCLEX-RN Prioritization, Delegation & Safety',
    description: 'Triage decision-making, UAP/LPN scope of practice, and acute instability recognition.',
    category: 'NCLEX-RN Prep',
    folder_id: 'f-nclex',
    cards_count: 2,
    due_count: 2,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c-nclex-1',
        deck_id: 'deck-nclex-1',
        card_type: 'flashcard',
        front: 'What core clinical responsibilities must NEVER be delegated by an RN to an Unlicensed Assistive Personnel (UAP)?',
        back: 'The "EAT" responsibilities: Evaluation, Assessment, and Teaching.',
        explanation: 'UAPs can perform routine tasks on stable patients (vital signs, ambulation, hygiene, intake/output), but cannot analyze clinical data or educate.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-nclex-2',
        deck_id: 'deck-nclex-1',
        card_type: 'multiple_choice',
        front: 'Which newly admitted patient should the emergency nurse prioritize and assess FIRST?',
        back: 'A 28-year-old with acute severe asthma whose wheezing has abruptly stopped, with silent breath sounds',
        distractors: [
          'A 55-year-old with chronic emphysema and an SpO2 of 89% on room air',
          'A 40-year-old with a fractured tibia reporting 8/10 pain with strong distal pulses',
          'A 70-year-old with diabetes and a fasting blood glucose of 240 mg/dL'
        ],
        explanation: 'A "silent chest" in asthma signals critical airflow obstruction, respiratory muscle exhaustion, and impending asphyxial arrest.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'deck-maternal-1',
    title: 'Obstetrics & Neonatal Nursing Emergencies',
    description: 'Fetal heart tracings, postpartum hemorrhage, APGAR scoring, and preeclampsia care.',
    category: 'Maternal & Pediatrics',
    folder_id: 'f-maternal',
    cards_count: 2,
    due_count: 2,
    created_at: new Date().toISOString(),
    cards: [
      {
        id: 'c-mat-1',
        deck_id: 'deck-maternal-1',
        card_type: 'flashcard',
        front: 'In electronic fetal monitoring, what is the clinical etiology of Variable Decelerations, and what is the first nursing action?',
        back: 'Etiology: Umbilical Cord Compression (VEAL CHOP). First action: Reposition mother to left lateral side, discontinue oxytocin, give O2.',
        explanation: 'Variable decelerations drop abruptly with no uniform relationship to contractions; lateral repositioning relieves vena cava and cord compression.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'c-mat-2',
        deck_id: 'deck-maternal-1',
        card_type: 'multiple_choice',
        front: 'What is the immediate priority nursing intervention for a postpartum patient experiencing heavy vaginal bleeding with a boggy, displaced uterus?',
        back: 'Perform vigorous fundal massage until the uterus contracts and firms up.',
        distractors: [
          'Administer IV oxytocin as an immediate bolus push',
          'Insert an indwelling urinary catheter before examining the fundus',
          'Place the patient in Trendelenburg position and notify the provider'
        ],
        explanation: 'Uterine atony is the primary cause of early postpartum hemorrhage. Immediate fundal massage stimulates uterine contraction to compress open sinusoids.',
        ease_factor: 2.5,
        interval: 0,
        repetitions: 0,
        due_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
];
